name: tagged_builder
description: A new Flutter package project.
version: 1.0.0
homepage: 'https://selfstudio.fun'
repository: 'https://github.com/CodeEagle/tagged_builder'
environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: '>=1.17.0'
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  coverage: ^1.8.0
flutter: null
